###
///Buscar por id
curl -X GET http://localhost:3000/0


###
///Crear
curl -X POST -H "Content-Type: application/json" -d '{"Nombre_Empresa": "Wilches", "Dia_Visita": "Lunes", "Telefono_Contacto": "123456789", "Estado_ID_Estado_PK": 0}' http://localhost:3000/crear


###
//Actualizar
curl -X PUT -H "Content-Type: application/json" -d '{"Nombre_Empresa": "Wilches Actualizado", "Dia_Visita": "Lunes", "Telefono_Contacto": "987654321", "Estado_ID_Estado_PK": 1}' http://localhost:3000/actualizar/0

###
//Eliminar
curl -X DELETE http://localhost:3000/eliminar/0
