###
GET http://localhost:3001/read HTTP/1.1

###
POST http://localhost:3001/Create HTTP/1.1
Content-Type: application/json

{
    "id" : "12234579",
    "tipoid":1,
    "name1":"Admon",
    "name2":"2",
    "lastname1":"x",
    "lastname2":"x",
    "cel":"3104552860",
    "email":"admon@gmail.com",
    "contrasena":"0000"
}

###
GET http://localhost:3001/Read/12234579 HTTP/1.1

###
PUT http://localhost:3001/Update/12234579 HTTP/1.1
Content-Type: application/json

{
    "name1": "rest",
    "name2": "rest",
    "lastname1": "rest",
    "lastname2": "rest",
    "cel":"888888",
    "email":"rest@rest",
    "contrasena": "rest"
}

###
DELETE http://localhost:3001/Delete/12234579 HTTP/1.1